spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rahulkumarprajapati071/SPRING_BOOT_CONFIG-PROPERTIES.git
          clone-on-start: true
Management:
  security:
    enabled: false